// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY LUASSUNCAO.

// WARNING: This file has automatically been generated on Thu, 05 May 2022 12:28:54 -03.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "model.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

